### ISSUE TITLE
dictionaries do not work

### ISSUE THREAD

**Issue by baimafeima** [libpinyin/ibus-libpinyin#64] opened 2016-11-13 04:19 UTC
Under Preferences (left-click) > Dictionary there are several dictionary options. This appears to be a new feature not available in previous IBus versions. 

Do these dictionaries come with the installation or do they need to be downloaded and installed separately? 

I tried to activate them to no avail. They are important insofar as they will increase the accuracy with which libpinyin predicts what Chinese character will follow the next one when typing in pinyin.

Testing system: Solus (https://www.solus-project.com/)
https://dev.solus-project.com/T1528

**Comment by epico** [comment] 2016-11-14 02:46
It is already installed, but need to re-login to take effects.

**Comment by epico** [comment] 2016-11-16 05:40
Maybe caused by dconf key name also, like #66.

**Comment by epico** [comment] 2016-11-25 06:07
As commented above, just close this issue for now.

**Closed by epico** 2016-11-25 06:07 UTC

**Comment by baimafeima** [comment] 2017-03-04 06:01
This seems to be solved but I am unsure how these dictionaries actually "work". Are they overriding the existing word suggestion algorithm of the standard database? It would be helpful to add more information to the _preferences_ to explain how it works.

**Comment by epico** [comment] 2017-03-06 03:07
Actually it only lists the word there, not affects the existing word suggestion algorithm.

**Comment by baimafeima** [comment] 2017-03-21 14:34
`Actually it only lists the word there, not affects the existing word suggestion algorithm.`

What do you mean? In what way is it beneficial then to "activate" one of these dictionaries?

**Comment by epico** [comment] 2017-03-22 05:12
It will list more candidates after activated some dictionaries.
