### ISSUE TITLE
Can't input Chinese period and comma when enabled "show suggestions"

### ISSUE THREAD

**Issue by JunjieYuan** [libpinyin/ibus-libpinyin#170] opened 2019-04-05 09:12 UTC
Which distribution and version?: 
Fedora 29 and 30 (Beta)

Which desktop environment and version?: 
GNOME 3.32

Which session type?: 
Wayland

Which application and version?: 
Any

IBus version?: 
IBus 1.5.20

Issue description:
Can't input Chinese period and comma (more...?) when enabled "show suggestions"

Steps to reproduce:
1. Enable "Show suggestions"
2. Input some Chinese
1. Press period or comma

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by epico** [comment] 2019-05-17 03:51
Please try dnf upgrade with Fedora 30.
Is this issue still reproducible with Fedora 30?

I can't reproduce it with Fedora 29, I will try with Fedora 30 soon.

**Comment by JunjieYuan** [comment] 2019-05-17 04:43
> Please try dnf upgrade with Fedora 30.
> Is this issue still reproducible with Fedora 30?

Yes.

I think the conflict between "[,] [.] flip page" and "Show suggestions." causes this bug.

**Comment by epico** [comment] 2019-05-20 05:36
Fixed in https://github.com/epico/ibus-libpinyin .

**Closed** 2019-05-20 05:36 UTC
